// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7ysGcPTbDeiYx81wOj9vTZ0MKMFEZNHo',
    appId: '1:946030358554:web:63801ba20ca2bd730de1a3',
    messagingSenderId: '946030358554',
    projectId: 'yahala-9b386',
    authDomain: 'yahala-9b386.firebaseapp.com',
    storageBucket: 'yahala-9b386.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ1bWrQist8itSNlj6DeLqNSJ6UD6ni9E',
    appId: '1:946030358554:android:81d0661552f41b9d0de1a3',
    messagingSenderId: '946030358554',
    projectId: 'yahala-9b386',
    storageBucket: 'yahala-9b386.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbLEvhzOZQ__kCawFjSEB_3WgX4NpKmhA',
    appId: '1:946030358554:ios:e5d6bc23127fead90de1a3',
    messagingSenderId: '946030358554',
    projectId: 'yahala-9b386',
    storageBucket: 'yahala-9b386.firebasestorage.app',
    iosBundleId: 'com.yahala.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbLEvhzOZQ__kCawFjSEB_3WgX4NpKmhA',
    appId: '1:946030358554:ios:e5d6bc23127fead90de1a3',
    messagingSenderId: '946030358554',
    projectId: 'yahala-9b386',
    storageBucket: 'yahala-9b386.firebasestorage.app',
    iosBundleId: 'com.yahala.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7ysGcPTbDeiYx81wOj9vTZ0MKMFEZNHo',
    appId: '1:946030358554:web:3f3d30dab89641b70de1a3',
    messagingSenderId: '946030358554',
    projectId: 'yahala-9b386',
    authDomain: 'yahala-9b386.firebaseapp.com',
    storageBucket: 'yahala-9b386.firebasestorage.app',
  );

}
